### ISSUE TITLE
node-gyp rebuild issues with iojs-v3 and node-v4

### ISSUE THREAD

**Issue by eliias** [travis-ci/travis-ci#4771]
I have troubles with `npm install bcrypt` since `iojs-v3` and I first thought the problem might has to do with my travis config but it seems to be something different.

I tried to follow up the stack trace and found something that is related to v8 deprecations. I am not 100% sure cause I cannot reproduce this behavior on any of my systems (Mac OS X Yosemite and Ubuntu 14.04), but now I am running out of ideas.

What I have done:

```bash
npm i -S bcrypt
```

The result can be found here:
https://travis-ci.org/netiam/experiments/builds/79552806

The important part is:

```bash
make: Entering directory `/home/travis/build/netiam/experiments/node_modules/bcrypt/build'
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
In file included from /home/travis/.node-gyp/4.0.0/include/node/node.h:42:0,
                 from ../node_modules/nan/nan.h:24,
                 from ../src/bcrypt_node.cc:1:
/home/travis/.node-gyp/4.0.0/include/node/v8.h:336:1: error: expected unqualified-id before ‘using’
/home/travis/.node-gyp/4.0.0/include/node/v8.h:469:1: error: expected unqualified-id before ‘using’
/home/travis/.node-gyp/4.0.0/include/node/v8.h:852:1: error: expected unqualified-id before ‘using’
In file included from ../node_modules/nan/nan.h:184:0,
                 from ../src/bcrypt_node.cc:1:
../node_modules/nan/nan_maybe_43_inl.h:13:1: error: expected unqualified-id before ‘using’
```

I created an empty repository with just one dependency (`bcrypt`). So nothing else(except bcrypt itself, which builds against iojs-v3 btw.) should cause this issue.

**Comment by BanzaiMan** [comment]
[Google search](https://www.google.com/search?q=error%3A+expected+unqualified-id+before+%E2%80%98using%E2%80%99&oq=error%3A+expected+unqualified-id+before+%E2%80%98using%E2%80%99&aqs=chrome..69i57j69i58.269j0j4&sourceid=chrome&es_sm=119&ie=UTF-8#q=error:+expected+unqualified-id+before+%E2%80%98using%E2%80%99+gcc) indicates that there are bad source files. I am not sure why it works on your Mac or a Trusty machine; I am guessing that it is due to newer compilers that may be more forgiving of this kind of errors. Could you try [APT addon](http://docs.travis-ci.com/user/apt/) to use gcc 4.8?

**Comment by eliias** [comment]
I just tried it and it seems to fail at the same point.

Just to ensure I did everything the right way, here is my `.travis.yml`.
```
sudo: false
language: node_js
node_js:
  - "4"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
```

The failed build with `gcc-4.8` is here: https://travis-ci.org/netiam/experiments/builds/79561779
And here is the log:

```bash
> bcrypt@0.8.5 install /home/travis/build/netiam/experiments/node_modules/bcrypt
> node-gyp rebuild
make: Entering directory `/home/travis/build/netiam/experiments/node_modules/bcrypt/build'
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
In file included from /home/travis/.node-gyp/4.0.0/include/node/node.h:42:0,
                 from ../node_modules/nan/nan.h:24,
                 from ../src/bcrypt_node.cc:1:
/home/travis/.node-gyp/4.0.0/include/node/v8.h:336:1: error: expected unqualified-id before ‘using’
/home/travis/.node-gyp/4.0.0/include/node/v8.h:469:1: error: expected unqualified-id before ‘using’
/home/travis/.node-gyp/4.0.0/include/node/v8.h:852:1: error: expected unqualified-id before ‘using’
In file included from ../node_modules/nan/nan.h:184:0,
                 from ../src/bcrypt_node.cc:1:
```
It looks like I am not the only with the problem (https://github.com/ncb000gt/node.bcrypt.js/issues/334).
Maybe @defunctzombie can clear things up. I also had this issue with `iojs-v3` which might help a little.

**Comment by BanzaiMan** [comment]
Try g++-4.8 as well as gcc-4.8, please.

**Comment by BanzaiMan** [comment]
I believe those are C++ warnings.

**Comment by badboy** [comment]
These are C++ warnings/errors. You need to explicitely set the CXX env variable. See how [hiredis-node does it](https://github.com/redis/hiredis-node/blob/master/.travis.yml#L4).

**Comment by eliias** [comment]
@badboy Thanks.
Setting the compiler env did it.
https://travis-ci.org/netiam/experiments/builds/79563697

**Comment by defunctzombie** [comment]
IMO Travis ci needs to just provide the correct end to build for nodejs v4
otherwise it isn't really "supported". That way users won't have to go
through these weird settings for basic builds as most won't know where to
start.

**Comment by kaplas** [comment]
+1 for this one. I'm in the same boat as @defunctzombie ; IMHO Travis environments Should Just Work without any additional configs. I just spent a couple of work days banging my head to the wall because of this one, related to https://github.com/laverdet/node-fibers/issues/249 :/

Anyway, for the future readers: In https://github.com/travis-ci/travis-ci/issues/4856 @BanzaiMan just mentioned, that they are working on an update for this, but don't have an ETA yet. So big :+1: for them going forward with this one! :dancer:

**Comment by refack** [comment]
:+1:  first of all.
Sorry that I'm adding noise, but I hope the following snippet will make google point to this page (especially @eliias 's [comment](https://github.com/travis-ci/travis-ci/issues/4771#issuecomment-139061464) )
```
CXX(target) Release/obj.target/buffertools/buffertools.o
In file included from /home/travis/.node-gyp/4.1.2/include/node/node.h:42:0,
                 from ../buffertools.cc:17:
/home/travis/.node-gyp/4.1.2/include/node/v8.h:336:1: error: expected unqualified-id before ‘using’
/home/travis/.node-gyp/4.1.2/include/node/v8.h:469:1: error: expected unqualified-id before ‘using’
/home/travis/.node-gyp/4.1.2/include/node/v8.h:852:1: error: expected unqualified-id before ‘using’
../buffertools.cc:32:11: error: ‘v8::Handle’ has not been declared
../buffertools.cc:492:21: error: variable or field ‘RegisterModule’ declared void
../buffertools.cc:492:21: error: ‘Handle’ was not declared in this scope
../buffertools.cc:492:34: error: expected primary-expression before ‘>’ token
../buffertools.cc:492:36: error: ‘target’ was not declared in this scope
../buffertools.cc:506:1: error: ‘RegisterModule’ was not declared in this scope
make: *** [Release/obj.target/buffertools/buffertools.o] Error 1
```

**Comment by kylev** [comment]
FYI, this state of things persists to the present day. My Node.js 5.1.0 (now stable) project requires this additional config to work.

**Comment by arjunmehta** [comment]
Perhaps this issue could be addressed and referenced in [the docs](https://docs.travis-ci.com/user/languages/javascript-with-nodejs/) somewhere, to clearly communicate the issue. But yeah Travis should be supporting Node 4+ out of the box.

**Comment by BanzaiMan** [comment]
We now print a warning if the Node.js/io.js version requires a C++11-compliant compiler but one is not available. It points to our documentation https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements, which explains how to fix this problem under the circumstances.

I'm closing this now.

**Comment by kaplas** [comment]
@BanzaiMan Could you elaborate a bit on why this is/was such a difficult problem to address? I still don't completely understand why you couldn't just include the compiler automatically with Node.js >=4 projects? Warning + documentation are of course good things, thanx for those :)

**Comment by SamSaffron** [comment]
+1 just had the exact same issue with 

https://github.com/discourse/mini_racer

**Comment by timaschew** [comment]
For me this fixed it: Add these lines to your __.travis.yml__

```yaml
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
```

**Comment by willworks** [comment]
@timaschew THX, it works!

**Comment by imsnif** [comment]
@timaschew 's adjustment worked for me as well.

I was getting:
```
node ./download-chromedriver.js
> pty.js@0.3.1 install .../node_modules/pty.js
> node-gyp rebuild
(...)
../src/unix/pty.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE PtyFork(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/unix/pty.cc:222:34: warning: ignoring return value of ‘int chdir(const char*)’, declared with attribute warn_unused_result [-Wunused-result]
../../nan/nan_new.h: In function ‘v8::Local<T> Nan::imp::To(v8::Local<v8::Integer>) [with T = v8::Integer]’:
../../nan/nan_new.h:22:1: warning: control reaches end of non-void function [-Wreturn-type]
make: *** [Release/obj.target/pty/src/unix/pty.o] Error 1
```

**Comment by lzl124631x** [comment]
https://travis-ci.org/lzl124631x/liuzhenglai/jobs/371403448

I'm still seeing this issue even I specified `CXX` and other settings. Please help.
```
language: node_js
node_js:
  - "node"
env:
  - TEST_DIR=front-end
  - TEST_DIR=back-end CXX=g++-4.8
# https://github.com/travis-ci/travis-ci/issues/4771#issuecomment-241439984
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
script: cd $TEST_DIR && npm install && npm test
```

**Comment by edmorley** [comment]
> WTF. I downgraded the node version and it succeeded...?! Oh my time.

The log output for the failing build explains why this is:
```
node-pre-gyp ERR! Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.3/bcrypt_lib-v1.0.3-node-v64-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.3 and node@10.0.0 (node-v64 ABI) (falling back to source compile with node-gyp) 
```

Several node.js packages use the "try and download a prebuilt binary, otherwise fall back to building locally" pattern. However it's common for there to be a delay between new node releases, and the prebuilt binaries being made available. As such, there either needs to be a working node-gyp environment, or the node version needs to be changed to match those that have prebuilt binaries available.

**Comment by lzl124631x** [comment]
@edmorley Thanks for your explanation. I understand it was trying but failed to download the prebuilt binary, and fallback to building locally. But I thought the `CXX` related config was for "building locally" to be successful. However, I was still seeing errors like:
```
../../nan/nan_maybe_43_inl.h:112:15: error: ‘class v8::Object’ has no member named ‘ForceSet’
```
I think this is a bug in the source code of bcrypt?
