### ISSUE TITLE
Compile errors with Perl 5.20, 5.22, 5.24

### ISSUE THREAD

**Issue by leto** [travis-ci/travis-ci#6662]
My Math::GSL Perl module compiles and passes tests on Travis CI for Perl 5.14, 5.16, 5.18 and then runs into problems starting with 5.20:

```
xs/BLAS_wrap.1.15.c: In function ‘SWIG_AsCharPtrAndSize’:
xs/BLAS_wrap.1.15.c:1602:6: error: ‘bool’ undeclared (first use in this function)
```

which started on this build: https://travis-ci.org/leto/math--gsl/builds/164220872 , when I enabled the new versions of Perl.

CPANtesters is currently showing 84 PASS reports for Perls between 5.8.8 and 5.24, so I am inclined to believe this might be caused by Perl header files not being found in the Travis build VM. I cannot reproduce this locally on my Linux/Perl 5.20.1 setup and neither can other devs.

Math::GSL issue is here: https://github.com/leto/math--gsl/issues/101

**Comment by BanzaiMan** [comment]
I can reproduce the problem using the Docker image we use. https://docs.travis-ci.com/user/common-build-problems/#Running-a-Container-Based-Docker-Image-Locally My guess is that SWIG is generating some incorrect source.

I see plenty of error messages about `swig` not being found, for both 5.20+ jobs and 5.18 jobs. You are installing `swig2.0`, but that package does not provide executable `swig` http://packages.ubuntu.com/precise/amd64/swig2.0/filelist. It is not clear to me why it works with 5.18 and not on 5.20.

**Comment by leto** [comment]
@BanzaiMan those SWIG warnings are a bit of a red herring. They are generated when we try to detect the binary name. They also appear is this Travis Job on Perl 5.18 that passes: https://travis-ci.org/leto/math--gsl/jobs/164373678

This may have something to do with Perl compile flags being different on 5.18 vs 5.20 on the Travis VM. I will try starting a local Docker container and see if I can get a better idea of what is going on.

**Comment by leto** [comment]
I reproduced this as well. Also got rid of all those swig warnings when we detect the binary name: https://travis-ci.org/leto/math--gsl/jobs/164464982

Here are the differences in `perl -V` for versions 5.18 and 5.20 (nothing jumps out as very different between them) : 

```
travis@57e811cbcb82:/math--gsl$ diff -u /tmp/perl5*
--- /tmp/perl518	2016-10-02 18:14:04.132097012 +0000
+++ /tmp/perl520	2016-10-02 18:13:35.963120141 +0000
@@ -1,18 +1,17 @@
-Summary of my perl5 (revision 5 version 18 subversion 2) configuration:
+Summary of my perl5 (revision 5 version 20 subversion 0) configuration:

   Platform:
     osname=linux, osvers=3.13.0-29-generic, archname=x86_64-linux
     uname='linux 6392109c82bf 3.13.0-29-generic #53-ubuntu smp wed jun 4 21:00:20 utc 2014 x86_64 x86_64 x86_64 gnulinux '
-    config_args='-de -Dprefix=/home/travis/perl5/perlbrew/perls/5.18 -Aeval:scriptdir=/home/travis/perl5/perlbrew/perls/5.18/bin'
+    config_args='-de -Dprefix=/home/travis/perl5/perlbrew/perls/5.20 -Aeval:scriptdir=/home/travis/perl5/perlbrew/perls/5.20/bin'
     hint=recommended, useposix=true, d_sigaction=define
     useithreads=undef, usemultiplicity=undef
-    useperlio=define, d_sfio=undef, uselargefiles=define, usesocks=undef
     use64bitint=define, use64bitall=define, uselongdouble=undef
     usemymalloc=n, bincompat5005=undef
   Compiler:
-    cc='cc', ccflags ='-fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
+    cc='cc', ccflags ='-fwrapv -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
     optimize='-O2',
-    cppflags='-fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include'
+    cppflags='-fwrapv -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include'
     ccversion='', gccversion='4.6.3', gccosandvers=''
     intsize=4, longsize=8, ptrsize=8, doublesize=8, byteorder=12345678
     d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=16
@@ -20,7 +19,7 @@
     alignbytes=8, prototype=define
   Linker and Libraries:
     ld='cc', ldflags =' -fstack-protector -L/usr/local/lib'
-    libpth=/usr/local/lib /lib/x86_64-linux-gnu /lib/../lib /usr/lib/x86_64-linux-gnu /usr/lib/../lib /lib /usr/lib
+    libpth=/usr/local/lib /usr/lib/gcc/x86_64-linux-gnu/4.6/include-fixed /usr/include/x86_64-linux-gnu /usr/lib /lib/x86_64-linux-gnu /lib/../lib /usr/lib/x86_64-linux-gnu /usr/lib/../lib /lib
     libs=-lnsl -lgdbm -ldl -lm -lcrypt -lutil -lc -lgdbm_compat
     perllibs=-lnsl -ldl -lm -lcrypt -lutil -lc
     libc=libc-2.15.so, so=so, useshrplib=false, libperl=libperl.a
@@ -33,25 +32,25 @@
 Characteristics of this binary (from libperl):
   Compile-time options: HAS_TIMES PERLIO_LAYERS PERL_DONT_CREATE_GVSV
                         PERL_HASH_FUNC_ONE_AT_A_TIME_HARD PERL_MALLOC_WRAP
-                        PERL_PRESERVE_IVUV PERL_SAWAMPERSAND USE_64_BIT_ALL
-                        USE_64_BIT_INT USE_LARGE_FILES USE_LOCALE
-                        USE_LOCALE_COLLATE USE_LOCALE_CTYPE
+                        PERL_NEW_COPY_ON_WRITE PERL_PRESERVE_IVUV
+                        USE_64_BIT_ALL USE_64_BIT_INT USE_LARGE_FILES
+                        USE_LOCALE USE_LOCALE_COLLATE USE_LOCALE_CTYPE
                         USE_LOCALE_NUMERIC USE_PERLIO USE_PERL_ATOF
   Locally applied patches:
 	Devel::PatchPerl 1.30
   Built under linux
-  Compiled at Feb  5 2015 16:02:14
+  Compiled at Feb  5 2015 15:44:41
   %ENV:
     PERLBREW_BASHRC_VERSION="0.73"
     PERLBREW_HOME="/home/travis/.perlbrew"
-    PERLBREW_MANPATH="/home/travis/perl5/perlbrew/perls/5.18/man"
-    PERLBREW_PATH="/home/travis/perl5/perlbrew/bin:/home/travis/perl5/perlbrew/perls/5.18/bin"
-    PERLBREW_PERL="5.18"
+    PERLBREW_MANPATH="/home/travis/perl5/perlbrew/perls/5.20/man"
+    PERLBREW_PATH="/home/travis/perl5/perlbrew/bin:/home/travis/perl5/perlbrew/perls/5.20/bin"
+    PERLBREW_PERL="5.20"
     PERLBREW_ROOT="/home/travis/perl5/perlbrew"
     PERLBREW_VERSION="0.73"
   @INC:
-    /home/travis/perl5/perlbrew/perls/5.18/lib/site_perl/5.18.2/x86_64-linux
-    /home/travis/perl5/perlbrew/perls/5.18/lib/site_perl/5.18.2
-    /home/travis/perl5/perlbrew/perls/5.18/lib/5.18.2/x86_64-linux
-    /home/travis/perl5/perlbrew/perls/5.18/lib/5.18.2
+    /home/travis/perl5/perlbrew/perls/5.20/lib/site_perl/5.20.0/x86_64-linux
+    /home/travis/perl5/perlbrew/perls/5.20/lib/site_perl/5.20.0
+    /home/travis/perl5/perlbrew/perls/5.20/lib/5.20.0/x86_64-linux
+    /home/travis/perl5/perlbrew/perls/5.20/lib/5.20.0
     .
```

**Comment by leto** [comment]
I found a Debian bug which seems to be exactly the same problem:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=752024

The core issue is that swig 2.0.4 does not seem to be compatible with Perl 5.20 or newer, a bug which was fixed in swig 2.0.8. I have swig 2.0.12 locally and so I never ran into the problem. CPANtesters use the code that I generated, so they never run swig to generate code.

**Comment by BanzaiMan** [comment]
Thanks for following up. Since swig package only goes up to 2.0.4 on Precise, the only remedy would be to either compile swig yourself, or use Trusty. http://packages.ubuntu.com/trusty/swig

I'm closing this now.
