### ISSUE TITLE
PHP ImageMagick unable to install, requires input

### ISSUE THREAD

**Issue by svivian** [travis-ci/travis-ci#5000]
Job: https://travis-ci.org/q2a/question2answer/jobs/86950027

Previous builds have run fine, but the PHP 7 build I just added stops on the line

    Please provide the prefix of Imagemagick installation [autodetect] :

After some searching I found issue #781 which I've followed through and everything there I am already running. Seems like the line...

    printf "\n" | pecl install imagick

...is no longer working. How do I fix this?

**Comment by BanzaiMan** [comment]
How do you do this on your local machine?

**Comment by svivian** [comment]
I don't run travis on my machine. I run the unit tests and occasionally the other stuff, but only on my machine and not across multiple PHP versions.

**Comment by BanzaiMan** [comment]
Sorry about the confusion. How do you install ImageMagick on PHP 7 on your machine?

**Comment by svivian** [comment]
Sorry I don't understand what you're asking. The problem here is that the script requires keyboard input - if I was installing this on my machine I can press buttons, obviously.

The `printf "\n"` line is supposed to handle that. It works fine with the PHP 5.3/5.4/5.5, but not with PHP 7.

**Comment by BanzaiMan** [comment]
Is this still a problem? Recent builds are passing.

Upon further inspection, https://travis-ci.org/q2a/question2answer/jobs/86950027#L202 shows compilation error; I suspect the issue was something completely different.

**Comment by svivian** [comment]
The builds are passing because I removed PHP7 from the travis file.

How do I test whether it's working now, without adding yet more commits to my project?

**Comment by BanzaiMan** [comment]
You can try restarting an old build.

**Comment by BanzaiMan** [comment]
For builds on containers, you can try running it locally: https://docs.travis-ci.com/user/common-build-problems/#Running-a-Container-Based-Docker-Image-Locally

For GCE and Mac builds, email us at support@travis-ci.com and we'll get you set up with a debug VM, so you can investigate interactively.

Thanks.

**Comment by joepvd** [comment]
Closing.
