### ISSUE TITLE
Can't build with Ruby 1.8.7 because bundler(or rubygem) is too new

### ISSUE THREAD

**Issue by uu59** [travis-ci/travis-ci#1795]
https://travis-ci.org/uu59/grill/jobs/16077514

``` console
$ rvm use 1.8.7 --install --binary --fuzzy
Using /home/travis/.rvm/gems/ruby-1.8.7-p374
$ export BUNDLE_GEMFILE=$PWD/Gemfile
$ ruby --version
ruby 1.8.7 (2013-06-27 patchlevel 374) [x86_64-linux]
$ rvm --version
rvm 1.24.11 (latest-minor) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
$ gem --version
2.2.0
before_install
$ gem install bundler rspec
Fetching: bundler-1.5.1.gem (100%)
Successfully installed bundler-1.5.1
Fetching: rspec-core-2.14.7.gem (100%)
Successfully installed rspec-core-2.14.7
Fetching: diff-lcs-1.2.5.gem (100%)
Successfully installed diff-lcs-1.2.5
Fetching: rspec-expectations-2.14.4.gem (100%)
Successfully installed rspec-expectations-2.14.4
Fetching: rspec-mocks-2.14.4.gem (100%)
Successfully installed rspec-mocks-2.14.4
Fetching: rspec-2.14.1.gem (100%)
Successfully installed rspec-2.14.1
6 gems installed
$ bundle install
Fetching gem metadata from https://rubygems.org/.........
Fetching additional metadata from https://rubygems.org/..
Unfortunately, a fatal error has occurred. Please see the Bundler
troubleshooting documentation at http://bit.ly/bundler-issues. Thanks!
/home/travis/.rvm/rubies/ruby-1.8.7-p374/lib/ruby/site_ruby/1.8/rubygems/specification.rb:325:in `sort': undefined method `<=>' for nil:NilClass (NoMethodError)
```
