### ISSUE TITLE
Can't build with npm > 6.2.0

### ISSUE THREAD

**Issue by kopax** [travis-ci/travis-ci#10113]
Dear travis.

I can't build with **npm@6.4.1**

I have downgrade to **npm@6.2.0** and it pass in travis.

Both version work fine locally.

The command `npm install -g npm@6.2.0` is not working well in travis.

It seems two version of npm are already installed and the one used is not the one installed with this command.

I fixed it like this in `.travis.yml`:

```yml
    - npm i -g npm@6.1.0
    - p=$(which npm)
    - rm $p
    - ln -s /home/travis/.nvm/versions/node/v10.1.0/bin/npm $p || true
    - npm -v
```

**Fail:** https://travis-ci.org/bootstrap-styled/navigation-bar/jobs/427991555

```bash
npm WARN prepare removing existing node_modules/ before installation
npm ERR! code MODULE_NOT_FOUND
npm ERR! Cannot find module '../pack.js'
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2018-09-13T04_18_28_658Z-debug.log
The command "eval npm ci  " failed. Retrying, 2 of 3.
/home/travis/.travis/job_stages: line 240: ./node_modules/.bin/npm: No such file or directory
The command "eval npm ci  " failed. Retrying, 3 of 3.
/home/travis/.travis/job_stages: line 240: ./node_modules/.bin/npm: No such file or directory
The command "eval npm ci  " failed 3 times.
```

**Fixed:** https://travis-ci.org/bootstrap-styled/navigation-bar/jobs/427958381 **_(ugly symlink fix)_**

```bash
The command "npm run build" exited with 0.
cache.2
store build cache
0.00s
3.84snothing changed, not updating cache
Done. Your build exited with 0.
```

**This is not reliable** and in some case, travis runner fail to create the symlink (https://travis-ci.org/bootstrap-styled/navigation-bar/jobs/427976455):

```bash
/home/travis/.travis/job_stages: line 98: /home/travis/.nvm/versions/node/v10.1.0/bin/npm: Too many levels of symbolic links
```

Could you please help us understand why all our GitHub/Travis project are having this issue while non of our GitLab/Gitlab-CI project images are having this error.

Did you change something recently in your image? I believe Travis is having a weird bug. Is there a community available anywhere? #travis on freenode look dead.

Please let us know asap how we can fix our OpenSource projects.

Kind regards,

**Comment by cotsog** [comment]
@kopax It might be related to a recent change we made where we'll now call `npm ci` if there's a `package-lock.json` file in your repo. See https://changelog.travis-ci.com/npm-ci-support-62786. Could you tell us if that's the case?

Furthermore, could you try to remove your workaround and also remove the `cache:` snippet from your .travis.yml file? Please let us know the result.

Thanks!

**Comment by mtliendo** [comment]
Same with the OP, it fails on newer versions of npm, as mentioned, when a `package-lock.json` is present.  As suggested, I removed the `cache:` and everything worked.

https://travis-ci.org/mtliendo/slack-link-surfer/jobs/429096790

**Comment by lemoustachiste** [comment]
I encounter this issue too on 2 of my projects. In one of them it seems to have started when I added a `.npmrc` file, to enable to implementation of `semantic-release`. 

While I was doing an install manually of the latest npm version (`npm i -g npm@6`) in my travis.yml instruction, I had removed it and the problem persists, so I'd doubt this could be related to a npm version.

I had already found that manually deleting the cached data on Travis was preventing the issue (not between 2 builds), but I am curious about the implication in terms of build time to completely remove the cache instruction from the `travis.yml` file?

For reference:
```
$ export PATH=./node_modules/.bin:$PATH
Updating nvm
Using nodejs version from .nvmrc
nvm.install
3.10s$ nvm install $(< .nvmrc)
Downloading and installing node v9.11.1...
Downloading https://nodejs.org/dist/v9.11.1/node-v9.11.1-linux-x64.tar.xz...
Computing checksum with sha256sum
Checksums matched!
Now using node v9.11.1 (npm v5.6.0)
cache.1
Setting up build cache
$ export CASHER_DIR=${TRAVIS_HOME}/.casher
0.12s$ Installing caching utilities
0.00s
8.00sattempting to download cache archive
fetching PR.6/cache-linux-trusty-e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855--node-.tgz
fetching PR.6/cache--node-.tgz
fetching master/cache-linux-trusty-e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855--node-.tgz
found cache
0.00s
14.98sadding /home/travis/build/blockchain-certificates/blockcerts-verifier/node_modules to cache
creating directory /home/travis/build/blockchain-certificates/blockcerts-verifier/node_modules
$ node --version
v9.11.1
$ npm --version
6.4.1
$ nvm --version
0.33.11
11.36s$ npm ci
npm WARN prepare removing existing node_modules/ before installation
npm ERR! code MODULE_NOT_FOUND
npm ERR! Cannot find module '../pack.js'
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2018-09-18T11_11_27_851Z-debug.log
The command "eval npm ci  " failed. Retrying, 2 of 3.
/home/travis/.travis/job_stages: line 240: ./node_modules/.bin/npm: No such file or directory
The command "eval npm ci  " failed. Retrying, 3 of 3.
/home/travis/.travis/job_stages: line 240: ./node_modules/.bin/npm: No such file or directory
The command "eval npm ci  " failed 3 times.
The command "npm ci " failed and exited with 127 during
 ```

**Comment by BanzaiMan** [comment]
> I am curious about the implication in terms of build time to completely remove the cache instruction from the travis.yml file?

Removing the `cache` directive simply means that your build will be installing and compiling dependencies from scratch every time. The cache often cuts down on build time, but it could also be a source of stale or incompatible files that cause problems.

Our caching utility attempts to avoid common known incompatibilities (e.g., different Node.js versions), but, here, it seems that in some cases Node.js version is defined elsewhere and the incompatible binary files survive in the cache.

**Comment by BanzaiMan** [comment]
All in all, though, this case appears to be the case of bad caches, and there is not much more to do.

I'm closing this now, but if you feel strongly, do let us know.

**Comment by kopax** [comment]
@cotsog I have added to `.gitignore` the `package-lock.json` and removed it.

This is fine because these are modules and not application. For our application we need our lock file, can you tell me how I should do?

**Comment by lemoustachiste** [comment]
@BanzaiMan thanks for your reply. Anyway, correct me if I'm wrong, but it seems to me that the node_modules get reinstalled anyway, regardless of having the cache setting on or off. 

From a build that was using cache:
```
$ npm install 96.74s
```

latest build with no cache setting:
```
$ npm install 94.41s$ 
```

this was the setting:
```
cache:
  directories:
    - "node_modules"
```

**Comment by phavor** [comment]
Am using `npm@6.4.1` and removing `cache` from `.travis.yml` solved it for me

**Comment by JinJieTan** [comment]
The above methods have been tried, but I have been the Module not found ，It's terrible. Is this library so popular that it still has such a serious problem
